// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCow8Ml-uKHW9M35EaFgcj_vWxen3snvQA',
    appId: '1:315359101174:web:d40995de5ff10f2c95ecd7',
    messagingSenderId: '315359101174',
    projectId: 'dailypartner-ca8c0',
    authDomain: 'dailypartner-ca8c0.firebaseapp.com',
    storageBucket: 'dailypartner-ca8c0.firebasestorage.app',
    measurementId: 'G-1PZ5BFZEJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IAH-t7VfwHP6IrJRn5dj7Y28AwQLYh0',
    appId: '1:315359101174:android:49568fb018b27f4195ecd7',
    messagingSenderId: '315359101174',
    projectId: 'dailypartner-ca8c0',
    storageBucket: 'dailypartner-ca8c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYUzrkWXUMW7rFQbWbujgyMC1dK06TNo',
    appId: '1:315359101174:ios:1c1765b5074fa32d95ecd7',
    messagingSenderId: '315359101174',
    projectId: 'dailypartner-ca8c0',
    storageBucket: 'dailypartner-ca8c0.firebasestorage.app',
    iosBundleId: 'com.example.dailyPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEYUzrkWXUMW7rFQbWbujgyMC1dK06TNo',
    appId: '1:315359101174:ios:1c1765b5074fa32d95ecd7',
    messagingSenderId: '315359101174',
    projectId: 'dailypartner-ca8c0',
    storageBucket: 'dailypartner-ca8c0.firebasestorage.app',
    iosBundleId: 'com.example.dailyPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCow8Ml-uKHW9M35EaFgcj_vWxen3snvQA',
    appId: '1:315359101174:web:f9659f77663c35cb95ecd7',
    messagingSenderId: '315359101174',
    projectId: 'dailypartner-ca8c0',
    authDomain: 'dailypartner-ca8c0.firebaseapp.com',
    storageBucket: 'dailypartner-ca8c0.firebasestorage.app',
    measurementId: 'G-B4CNZ4V3XS',
  );
}
